// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("oxen")>]
[<assembly: AssemblyProductAttribute("oxen")>]
[<assembly: AssemblyDescriptionAttribute("fsharp implementation of Optimalbits/bull")>]
[<assembly: AssemblyVersionAttribute("0.4.2")>]
[<assembly: AssemblyFileVersionAttribute("0.4.2")>]
[<assembly: InternalsVisibleToAttribute("oxen.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "oxen"
    let [<Literal>] AssemblyProduct = "oxen"
    let [<Literal>] AssemblyDescription = "fsharp implementation of Optimalbits/bull"
    let [<Literal>] AssemblyVersion = "0.4.2"
    let [<Literal>] AssemblyFileVersion = "0.4.2"
    let [<Literal>] InternalsVisibleTo = "oxen.Tests"
